### ISSUE TITLE
Installation Instructions for Existing pre-commit installation with pipx

### ISSUE THREAD

**Issue by Eutropios** [tox-dev/pre-commit-uv#3]
Since there aren't any installation instructions listed for an existing pre-commit installation with pipx, I had to figure it out myself.
*Attempting to install pre-commit-uv with pipx will not work!*
You must patch it as shown in this example. Installing pre-commit-uv with pipx as `pipx install pre-commit-uv` will not install a binary onto your system.

Reqs: pipx is already installed, an existing pipx-created pre-commit installation exists on your system. An existing uv installation is not required, as this process will install it for you inside of the pre-commit isolated environment.

```bash
pipx runpip pre-commit install pre-commit-uv
```

`runpip <package>` tells pipx to run the environment associated with `<package>`, in this case the environment associated with pre-commit.

**Comment by gaborbernat** [comment]
I think the more straightforward approach is to do:

pipx install pre-commit
pipx inject pre-commit pre-commit-uv

**Comment by Eutropios** [comment]
Yeah, that seems more starightforward. Not sure why I didn't think of that.

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/pre-commit-uv/commit/fdb8619d674b22749830023e8a45effb24b16fd8
